# Färger från wallpaper
background            #0f1416
foreground            #dee3e5
selection_background  #84d2e6
selection_foreground  #0f1416

# Cursor
cursor                #84d2e6
cursor_text_color     #0f1416

# Borders
active_border_color   #84d2e6
inactive_border_color #1b2122

# Svarta
color0  #0f1416
color8  #3f484b

# Röda
color1  #b85766
color9  #b85766

# Gröna (cyan i vårt fall)
color2  #84d2e6
color10 #a9edff

# Gula
color3  #bec5eb
color11 #dde1ff

# Blåa
color4  #004e5c
color12 #006879

# Magentas
color5  #b2cbd2
color13 #cee7ee

# Cyaner
color6  #84d2e6
color14 #a9edff

# Vita
color7  #dee3e5
color15 #ffffff

# Font
font_family      JetBrains Mono
font_size        12.0

# Padding
window_padding_width 12

# Opacity
background_opacity 0.95
